Adatbázisok:

Fájl1: A különböző napokra tárolja el, hogy kik jelentkeztek. Ebből kivehető a programokhoz szükséges regisztrációs adatok is.
Fájl2: Tartalmazza az összes árat
Fájl3: Tartalmazza az összes programot és az elérhető helyeket
Féjl4: Statisztika (Extra)

Köszönő üzenet

Bekérés:

Regisztráló alapvető adatai, illetve kapjon egy ID-t is amit az adatbázisokhoz tudunk használni
Milyen nap?
Hány ember?
;Csak akkor engedje tovább ha van annyi elérhető hely aznapra
-Írja ki a személy típusokat
Hány felnőtt, gyerek, nyugdíjas, ... típusú személy?
;Igazából addig kérdezze végig ameddig nem lesz a kiválasztott személyek összege annyi amennyi a 2. Bekérésben megadott személyek elemszáma
Ajánljon fel esetleges kedvezményes opciókat ehhez mérten pl. csoportos, családi jegy stb.
-Írja ki a kombinált árat
Kérdezzen rá, hogy szeretne-e programokra menni.
Ha szeretne, akkor listázza az arra a napra még elérhető programokat és az elérhető helyeket.
Kérdezze meg, hogy melyikre szeretne menni
Kérdezze meg, hogy hány fővel
;Véglegesítés, fizetés
-Jegy kiadása, legyen rajta egy kód, a név, a jegyek típusai, ár, igazából az összes eddigi információ

Működés:

A bekérések logikusak, nyilván vannak elágazások pl. az elérhető helyek leellenőrzésénél, programok választásánál, ezt a fenti szöveg alapján ki lehet találni.
Igazából mindent a fájlokból olvasunk ki, töltünk fel.
Az adatbázisok 3 fájlra bontódnak.
Az elsőbe írjuk a bekérések első részét, igazából addig érdekes, hogy ki jelentkezik és hányan, a többi a számítások szempontjából mindegy.
A másik fájlt arra kell, hogy az árakat egy helyen lehessen módosítani, majd úgy oldjuk meg, hogy minden ár kap egy ID-t, s igazából azt a számot írja majd be a vásárló, a kiírásnál egyértelmű lesz neki.
A harmadik végül a programokat tartalmazza. Igazából itt is ID alapján megy majd. Hétfő, kedd, szerda... 1,2,3.. ID és az azokon belüliek időrend szerint 11, 12.. vagy ugye 21, 22.. stb.

Extra:
A folyamat bármikor legyen megszűntethető a "kilépés" szó beírásával

Esetleges Statisztika vezetése pl. legpopulárisabb napok, programok, összbevétel, de ez tényleg extra